services:
  backend:
    image: ghcr.io/ognjenmanojlovic/conduit-container-backend:latest
    env_file:
      - ./.env
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    networks:
      - conduit-network
    restart: unless-stopped
    volumes:
      - db-data:/data

  frontend:
    image: ghcr.io/ognjenmanojlovic/conduit-container-frontend:latest
    env_file:
      - ./.env
    depends_on:
      - backend
    ports:
      - "${FRONTEND_PORT:-8282}:80"
    networks:
      - conduit-network
    restart: unless-stopped

networks:
  conduit-network:
    driver: bridge

volumes:
  db-data:
